name: Publish OpenAPI Spec to APIHub
description: Runs swaggerhub cli to push openapi jarfile to APIHub

on:
  workflow_call:
    inputs:
      swaggerhub_api_key:
        required: true
        type: string
      upload_artifact_name:
        required: true
        type: string
      apihub_owner:
        required: true
        type: string
      api_name:
        required: true
        type: string
      api_version:
        required: true
        type: string
      is_release:
        required: false
        type: boolean
        default: false

runs:
  using: "composite"
  steps:
    - name: Step one
      shell: bash
      run: |
        echo "Got inputs.api_name ${inputs.api_name}"